### ISSUE TITLE
Error: toggleTokenSimulation is not a registered action

### ISSUE THREAD

**Issue by Bullfrog1234** [camunda/camunda-modeler-token-simulation-plugin#101]
__Describe the Bug__

I get the following error on loading the plugin and trying to `toggleTokenSimulator` action

````
toggleTokenSimulation is not a registered action
    at s (x86)/Camunda%20Modeler/resources/app.asar/public/465.js:5:141408)
    at r.trigger (x86)/Camunda%20Modeler/resources/app.asar/public/465.js:5:142504)
    at oe.triggerAction (x86)/Camunda%20Modeler/resources/app.asar/public/827.js:1:12455)
    at x.triggerAction (x86)/Camunda%20Modeler/resources/app.asar/public/508.js:1:3563)
    at n.triggerAction (x86)/Camunda%20Modeler/resources/app.asar/public/508.js:1:6218)
    at file:///C:/Program%20Files%20(x86)/Camunda%20Modeler/resources/app.asar/public/bundle.js:2:3598278 (x86)/Camunda%20Modeler/resources/app.asar/public/bundle.js:2:3598278)
    at bk.triggerAction (x86)/Camunda%20Modeler/resources/app.asar/public/bundle.js:2:3595810)
    at file:///C:/Program%20Files%20(x86)/Camunda%20Modeler/resources/app.asar/public/bundle.js:2:3602816 (x86)/Camunda%20Modeler/resources/app.asar/public/bundle.js:2:3602816)
    at Sk.triggerAction (x86)/Camunda%20Modeler/resources/app.asar/public/bundle.js:2:3602892)
    at file:///C:/Program%20Files%20(x86)/Camunda%20Modeler/resources/app.asar/public/bundle.js:2:3606059 (x86)/Camunda%20Modeler/resources/app.asar/public/bundle.js:2:3606059) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
````

__Steps to Reproduce__

1. Add plugin to plugins directory
2. Load Camunda Modeler
3. Try to toggle token simulator on

__Expected Behavior__

Token simulator loads and works

__Environment__

- OS: Windows 11
- Plugin version: v0.20.0
- Modeler Version: V5.24.0

**Comment by barmac** [comment]
I cannot reproduce this on MacOS. Can you please share a screencast with exact steps that you took?

**Comment by barmac** [comment]
Please also run `git log` in the plugin directory and share the result.

**Comment by Bullfrog1234** [comment]
Will do that in 2 days time. I am away for work and don't have access to the correct computer until Thursday night to complete the task.

**Comment by barmac** [comment]
Do you have any updates on this? Otherwise, I will close the issue as `invalid`.

**Comment by Bullfrog1234** [comment]
Give me another 3 days and I will get this to you. Sorry been moving house and not even thought about it.

**Comment by barmac** [comment]
Sure, take your time.

**Comment by Bullfrog1234** [comment]
Here is the log

````
commit 6aa7388b8e38109c8a4b0d41c96857d832653090 (HEAD -> main, origin/main, origin/HEAD)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Mon Jul 15 11:11:40 2024 +0200

    deps: bump bpmn-js from 17.9.0 to 17.9.1

commit 2a2bcbb04058e2765966c7f0181fe8f95d7fe97f
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Mon Jul 1 11:04:18 2024 +0000

    deps: bump bpmn-js from 17.8.2 to 17.9.0

    Bumps [bpmn-js](https://github.com/bpmn-io/bpmn-js) from 17.8.2 to 17.9.0.
    - [Release notes](https://github.com/bpmn-io/bpmn-js/releases)
    - [Changelog](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md)
    - [Commits](https://github.com/bpmn-io/bpmn-js/compare/v17.8.2...v17.9.0)

    ---
    updated-dependencies:
    - dependency-name: bpmn-js
      dependency-type: direct:development
      update-type: version-update:semver-minor
    ...

    Signed-off-by: dependabot[bot] <support@github.com>

commit 92fcf47d1e8d9f6dcdf7a86933bf74e03b172263
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Mon Jun 24 11:49:24 2024 +0000
````
